apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking

data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: bankingdb

  SPRING_PROFILES_ACTIVE: prod

  APP_NAME: banking-app