apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: banking
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: bankingdb
  MYSQL_USER: bankinguser
  MYSQL_PASSWORD: banking123